name: predict_my_mood
description: A new Flutter project.

publish_to: 'none' # This indicates the project won't be published to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.18.0 # Match the version required by flutter_test.
  async: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Downgraded to the compatible version.

flutter:
  uses-material-design: true

  assets:
    - images/
